[template]
src = "nginx.conf.tmpl"
dest = "/etc/nginx/nginx.conf"
keys = [
    "/kubernetes/service/host",
    "/kubernetes/service/port",
    "/maestrod/service/host",
    "/maestrod/service/port",
]
check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
reload_cmd = "/usr/sbin/nginx -s reload"

