kind: ReplicationController
apiVersion: v1
metadata:
    name: nginx
    labels:
        name: nginx
spec:
    replicas: 1
    selector:
        name: nginx
    template:
        metadata:
            labels:
                name: nginx
        spec:
            containers:
                - name: nginx
                  image: cpg1111/maestro-demo-nginx
                  ports:
                      - name: nginxinsecure
                        containerPort: 80
                        protocol: TCP
                      - name: nginxsecure
                        containerPort: 443
                        protocol: TCP
