kind: ReplicationController
apiVersion: v1
metadata:
    name: maestrod
spec:
    replicas: 1
    selector:
        name: maestrod
    template:
        metadata:
            labels:
                name: maestrod
        spec:
            containers:
                - name: maestrod
                  image: cpg1111/maestrod:0.1.1-rc0
                  ports:
                      - name: maestrod-hooks
                        containerPort: 8888
                        protocol: TCP
                      - name: maestrod-state
                        containerPort: 8889
                        protocol: TCP
                  volumeMounts:
                      - name: conf
                        mountPath: /etc/maestrod/
            volumes:
                - name: conf
                  hostPath:
                      path: /etc/maestrod/
