kind: ReplicationController
apiVersion: v1
metadata:
    name: maestrod
    lables:
        name: maestrod
spec:
    replicas: 1
    selector:
        name: maestrod
    template:
        metadata:
            labels:
                name: maestrod
        spec:
            containers:
                - name: maestrod
                  image: cpg1111/maestrod:latest
                  ports:
                      - name: maestrod
                        containerPort: 8888
                        protocol: TCP
                  volumeMounts:
                      - name: conf
                        mountPath: /etc/maestrod/
                  readinessProbe:
                      httpGet:
                          path: /healthz/
                          port: 8888
            volumes:
                - name: conf
                  hostPath:
                      path: /etc/maestrod/

