kind: Service
apiVersion: v1
metadata:
    name: maestrod
    labels:
        name: maestrod
spec:
    ports:
        - name: maestrod-hooks
          protocol: TCP
          port: 8888
          targetPort: 8888
        - name: maestrod-state
          protocol: TCP
          port: 8889
          targetPort: 8889
    selector:
        name: maestrod
    sessionAffinity: ClientIP
    type: ClusterIP
