kind: Service
apiVersion: v1
metadata:
    name: maestrod
    labels:
        name: maestrod
spec:
    ports:
        - protocol: TCP
          port: 8888
          targetPort: 8888
    selector:
        name: maestrod
    sessionAffinity: ClientIP
    type: ClusterIP

