[Environment]
Env=[]
ExecSync=[
    "mkdir -p /root/.ssh/ /root/.docker/",
    "cp /etc/maestrod/creds.d/id_rsa /root/.ssh/id_rsa",
    "cp /etc/maestrod/creds.d/id_rsa /root/.ssh/id_rsa",
    "cp /etc/maestrod/creds.d/config.json /root/.docker/"
]
Exec=[]

[Project]
RepoURL="git@github.com:cpg1111/demo-maestro-app.git"
CloneCMD="git clone"
AuthType="SSH"
SSHPrivKeyPath="~/.ssh/id_rsa"
SSHPubKeyPath="~/.ssh/id_rsa.pub"
Username="git"
Password=""
PromptForPWD=false

[[Services]]
Name="db"
Tag="0.1.1"
TagType="git"
Path="./services/db"
BuildLogFilePath="/var/log/maestro/db.log"
BuildCMD=["docker build -t cpg1111/demo-maestro-db:{{.Curr}} .", "docker tag cpg1111/demo-maestro-db:{{.Curr}} demo_db"]
TestCMD=["docker run --rm cpg1111/demo-maestro-db:{{.Curr}} test"]
CheckCMD=["echo 'no check'"]
CreateCMD=["docker push cpg1111/demo-maestro-db:{{.Curr}}"]
UpdateCMD=["docker push cpg1111/demo-maestro-db:{{.Curr}}"]
DependsOn=[]

[[Services]]
Name="auth"
Tag="0.1.0"
TagType="git"
Path="./services/auth"
BuildLogFilePath="/var/log/maestro/auth.log"
BuildCMD=["docker build -t cpg1111/demo-maestro-auth:{{.Curr}} ."]
TestCMD=["docker run --rm cpg1111/demo-maestro-auth:{{.Curr}} test"]
CheckCMD=["echo 'no check'"]
CreateCMD=["docker push cpg1111/demo-maestro-auth:{{.Curr}}", "kubectl create -f ./rc.yml"]
UpdateCMD=[
    "docker push cpg1111/demo-maestro-auth:{{.Curr}}",
    "kubectl rolling-update auth --image=cpg1111/demo-maestro-auth:{{.Curr}}"
]
DependsOn=["db"]

[[Services]]
Name="chat"
Tag="0.1.1"
TagType="git"
Path="./services/chat"
BuildLogFilePath="/var/log/maestro/chat.log"
BuildCMD=["docker build -t cpg1111/demo-maestro-chat:{{.Curr}} ."]
TestCMD=["docker run --rm cpg1111/demo-maestro-chat:{{.Curr}} test"]
CheckCMD=["echo 'no check'"]
CreateCMD=[
    "docker push cpg1111/demo-maestro-chat:{{.Curr}}",
    "kubectl create -f ./rc.yml"
]
UpdateCMD=[
    "docker push cpg1111/demo-maestro-chat:{{.Curr}}",
    "kubectl rolling-update chat --image=cpg1111/demo-maestro-chat:{{.Curr}}"
]
DependsOn=["db"]

[[Services]]
Name="client"
Tag="0.1.1"
TagType="git"
BuildLogFilePath="/var/log/maestro/client.log"
BuildCMD=["gulp build", "docker build -t cpg1111/demo-maestro-client:{{.Curr}} ."]
TestCMD=["docker run --rm cpg1111/demo-maestro-clien:{{.Curr}} test"]
CheckCMD=["echo 'no check'"]
CreateCMD=["docker push cpg1111/demo-maestro-client:{{.Curr}}", "kubectl create -f ./rc.yml"]
UpdateCMD=[
    "docker push cpg1111/demo-maestro-client:{{.Curr}}"
]
DependsOn=["db"]
