[Server]
Runtime="k8s"
MaxBuilds=6
DataStoreType="etcd2"
DataStoreIP="45.55.67.79"
DataStorePort=2379
TargetProtocol="http"
TargetHost="45.55.67.79"
TargetPort="8080"
MaestroVersion="0.3.4-rc4"
Host="0.0.0.0"
InsecurePort=8888
StateComPort=8889
WorkspaceDir="/tmp/src/"

[[Projects]]
Name="cpg1111/demo-maestro-app"
MaestroConfPath="/etc/maestrod/conf.d/demo-maestro-app.toml"
DeployBranches=["master"]
