[Server]
Runtime="k8s"
MaxBuilds=6
DataStoreType="etcd"
DataStoreEnvIP="ETCD_SERVICE_HOST"
DataStoreEnvPort="ETCD_SERVICE_PORT"
TargetProtocol="http"
TargetEnvHost="KUBERNETES_SERVICE_HOST"
TargetEnvPort="KUBERNETES_SERVICE_PORT"
MaestroVersion="0.3.2"
Host="0.0.0.0"
InsecurePort=8888
WorkspaceDir="/tmp/"

[[Projects]]
Name="cpg1111/demo-maestro-app"
MaestroConfPath="/etc/maestrod/conf.d/demo-maestro-app.toml"
DeployBranches=["master"]

